modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="goatskitchen" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Goat's Kitchen" #mandatory
credits="MightyGoat, VakyPanda, Coda" #optional
description='''Do you have what it takes to become a master chef?'''